### ISSUE TITLE
简化 import 然后直接 export 写法

### ISSUE THREAD

**Issue by warmhug** [ant-design/babel-plugin-antd#14]
原写法：
![image](https://cloud.githubusercontent.com/assets/2011119/14812162/8230cc78-0bce-11e6-80bf-70666d6298b0.png)

希望的写法：
<img width="387" alt="47d807b5334032e5aec2472876c8188f" src="https://cloud.githubusercontent.com/assets/2011119/14812177/96fb3f08-0bce-11e6-88ee-2ac7cd148a2d.png">

**Comment by sorrycc** [comment]
没太明白，你希望在 `babel-plugin-antd` 层做什么样的支持，展开说下？现在 `babel-plugin-antd` 处理的是 import 的部分，export 并没有处理。

**Comment by warmhug** [comment]
就是能直接这么写 
```
export { List, Flex... } from 'antm';
```

**Comment by sorrycc** [comment]
和 #21 重复。
