### ISSUE TITLE
Using babel-plugin-antd still get warning

### ISSUE THREAD

**Issue by LiuuY** [ant-design/babel-plugin-antd#16]
Using this plugin in package.json:

`  "babel": {
    "presets": [
      "es2015",
      "react"
    ],
    "plugins": [
      "babel-plugin-antd"
    ]
  }`

But chrome still warned me that 

> you are using prebuild antd,
> please use https://github.com/ant-design/babel-plugin-antd to reduce app bundle size.
> 

ENV: 
antd: 1.0.0
babel-plugin-antd: 0.4.0

**Comment by Yuliang-Lee** [comment]
我有相同的问题

**Comment by afc163** [comment]
可以参考：https://github.com/ant-design/antd-init/blob/24ccda108d4ca45bc9d02a79c6d1df511ad53966/boilerplate/webpack.config.js#L2
