### ISSUE TITLE
怎么使用babel-plugin-antd这个插件呢?

### ISSUE THREAD

**Issue by laolu87** [ant-design/babel-plugin-antd#17]
浏览器控制台提示'you are using prebuild antd,
please use https://github.com/ant-design/babel-plugin-antd to reduce app bundle size.',
需要怎么使用这个插件消除这个提示呢?麻烦提供一下具体点的配置教程!

**Comment by sorrycc** [comment]
@afc163 这个提示是根据什么判断做出的?

**Comment by pigcan** [comment]
同问

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/blob/master/index.js

走这个文件就会出现，直接 `import 'antd/lib/xxx'` 或是用了 babel-plugin-antd 就不会出现，楼主应该是不会配置 babel-plugin

**Comment by afc163** [comment]
#18

**Comment by laolu87** [comment]
@afc163 我也知道直接 import 'antd/lib/xxx'，不会出现提示，但问题是这样做的话引用的组件一多就非常麻烦了，所以才想问问怎么使用babel-plugin-antd。具体要配置哪里呢？

**Comment by Catlite91** [comment]
报错：Module build failed: Error: Plugin 1 specified in "/Users/panda/workspace/olympus/mobile/.babelrc" provided an invalid property of "style" 

.babelrc添加配置：
 "plugins": [
    "antd", {"style": true}
  ]
请问是这么配置么？

**Comment by guimuv5** [comment]
同问

**Comment by afc163** [comment]
https://github.com/ant-design/babel-plugin-antd#usage

**Comment by laolu87** [comment]
前两天一直在忙着研究组件,今天再看了一下,终于把问题解决了.按官方文档先安装babel-plugin-antd,然后在webpack.config.js的loaders里面jsx这一项添加一个plugins: [['antd', {style:'css'}]],就可以了.希望对有相同问题的同学有用.

**Comment by Witee** [comment]
还是不能用，报错：
Module build failed: TypeError: The plugin ["antd",{"style":"css"}] didn't export a Plugin instance

**Comment by hust419** [comment]
babel-plugin-antd 的文档也太简单了，完全不知所云。
依然搞不清楚，为什么会出现这个提示？ 为什么要有这个提示。
为什么要用babel-plugin-antd，用了有什么好处
怎么用babel-plugin-antd...... 一堆疑问

**Comment by Witee** [comment]
我当时的解决办法是 babel 版本升级到6以上，之前用的是5，但随之会引来新的问题，google 后解决

**Comment by leinov** [comment]
同问呀

**Comment by lcoder** [comment]
@hust419    对的，完全搞不清楚这个插件是干嘛的。

**Comment by biggeryan** [comment]
https://ant.design/docs/react/getting-started-cn文档里面有说明的

**Comment by FairyRoc** [comment]
您好，使用babel-plugin-import的时候经常会有一个问题：当我加载一个子Component的时候，它会引起import插件的自动加载style功能，例如import {Menu,SubMenu} from 'antd'，就会报错sub-menu/style不存在，请问有什么方法解决吗？谢谢

**Comment by hansinhu** [comment]
Note：
babel-plugin-import will be not working if you add the library in webpack config vendor.
