### ISSUE TITLE
如何在webpack中做配置？

### ISSUE THREAD

**Issue by cnfi** [ant-design/babel-plugin-antd#18]
以下代码怎么添加？
```
loaders: [
		  {
		      test: /\.jsx?$/,
		      exclude: /(node_modules|bower_components)/,
		      loader: 'babel',
		      query: {
		        presets: ['react', 'es2015', 'stage-0']
		      }
		    }
		]

```

**Comment by sorrycc** [comment]
如果基于 atool-build，参考脚手架：
https://github.com/ant-design/antd-init/blob/master/boilerplate/webpack.config.js#L2-L4

如果直接基于 webpack，修改 .babelrc：
https://github.com/ant-design/babel-plugin-antd#via-babelrc

**Comment by cnfi** [comment]
按照文档写的还是报错

 .babelrc中

```
{
	presets: ['react', 'es2015', 'stage-0'],
	plugins: ['antd', {style: 'css'}]
}
```

报错：Module build failed: Error: Plugin 1 specified in "/Users/cnfi/Documents/xxxxx/.babelrc" provided an invalid property of "style"

**Comment by afc163** [comment]
https://github.com/ant-design/babel-plugin-antd#usage

注意格式。
