### ISSUE TITLE
文档中的.babelrc写法是不是有错误？

### ISSUE THREAD

**Issue by shengliangli** [ant-design/babel-plugin-antd#19]
文档中的.写法是：
{
  "plugins": ["antd", options]
}

webpack 直接报错

改成：
{
  "plugins": [["antd", options]]
}
(多了一对中括号)
不报错，但是webpack 编译后，运行，浏览器报告警告：
you are using prebuild antd,
please use https://github.com/ant-design/babel-plugin-antd to reduce app bundle size.

求解！！！

**Comment by sorrycc** [comment]
是的，感谢提醒。
