### ISSUE TITLE
求大神解答下

### ISSUE THREAD

**Issue by holoto** [ant-design/babel-plugin-antd#20]
## babelrc配置
"plugins": [["antd", {"style":'css'}]],
## chrome报错
`template_of_912_referencing_39:13 Uncaught ReferenceError: __webpack_module_template_argument_1____webpack_module_template_argument_2__ is not defined`

**Comment by afc163** [comment]
看看是否 0.4.0 版本。

**Comment by holoto** [comment]
版本是0.4.0

**Comment by afc163** [comment]
https://github.com/ant-design/babel-plugin-antd#usage

**Comment by holoto** [comment]
# 已解决
