### ISSUE TITLE
Looks good, but will this be replaced by webpack 2.0?

### ISSUE THREAD

**Issue by supnate** [ant-design/babel-plugin-antd#23]
Just a question.
Since webpack 2.0 will support tree-shaking: http://www.2ality.com/2015/12/webpack-tree-shaking.html
In my mind it will provide the same result with this plugin.

**Comment by sorrycc** [comment]
Nope. 

In my impression, tree-shaking behave differently from this plugin. And babel-plugin-antd support other features, such as `CSS Auto Import`.
