### ISSUE TITLE
样式按需加载能否详细点

### ISSUE THREAD

**Issue by swim1986** [ant-design/babel-plugin-antd#24]
如果使用css的话应该怎么配置.babelrc?

**Comment by sorrycc** [comment]
https://github.com/ant-design/babel-plugin-antd#usage

```
{
  "plugins": [["antd",{style:"css"}]]
}
```

**Comment by Mickey-** [comment]
有点疑惑，设为true和‘css’的差异是什么?
引用less和引用css的差异吗 @sorrycc

**Comment by sorrycc** [comment]
@Mickey- 是的。
