### ISSUE TITLE
babel-plugin-antd 使用问题

### ISSUE THREAD

**Issue by blackMao** [ant-design/babel-plugin-antd#31]
配置内容：
{
  "stage": 0,
  "env": {
    "development": {
      **"plugins": ["react-transform", "antd"],**
      "extra": {
        "react-transform": {
          "transforms": [{
            "transform": "react-transform-hmr",
            "imports": ["react"],
            "locals": ["module"]
          }, {
            "transform": "react-transform-catch-errors",
            "imports": ["react", "redbox-react"]
          }]
        }
      }
    }
  }
}

错误信息：
Module build failed: **TypeError: The plugin "antd" didn't export a Plugin instance**

请问哪里配置错误了？应该怎么配置，是否有例子？

**Comment by jiushiwoyuze** [comment]
在webpack.config中加入
    babel: {
      "plugins": [["antd"]]
    }

**Comment by blackMao** [comment]
@jiushiwoyuze 有完整的webpack.config文件吗？

**Comment by jiushiwoyuze** [comment]
以下是我这边的config，可以参考下
var webpack = require('webpack');

module.exports = {
    entry: [
      'webpack/hot/only-dev-server',
      "./js/app.js"
    ],
    output: {
        path: './build',
        filename: "bundle.js"
    },
    module: {
        loaders: [
            { test: /\.js$/, exclude: /node_modules/, loader: 'babel-loader'},
            { test: /\.css$/, loader: "style!css" },
            {test: /\.less/,loader: 'style-loader!css-loader!less-loader'},
            {
              test: /\.js$/,
              exclude: /node_modules/,
              loader: "babel-loader",
              query:
                {
                  presets:['react','es2015']
                }
            }
        ]
    },
    resolve:{
        extensions:['','.js','.json']
    },
    devServer: {
        hot: true,
        inline: true
    },
    plugins: [
      new webpack.NoErrorsPlugin(),
      new webpack.HotModuleReplacementPlugin()
    ],
    babel: {
      "plugins": [["antd"]]
    }
};

**Comment by blackMao** [comment]
@jiushiwoyuze 我试了一下 还是不行

**Comment by pigcan** [comment]
反馈问题的时候最好说明下自己的平台，node 的版本，npm 版本，自己引入的 webpack 的版本。
另外为了我们能更好的阅读你反馈的问题也建议你至少格式化你贴的代码。

至于配置如何写，可以参考

https://github.com/ant-tool/atool-build/blob/master/src/getWebpackCommonConfig.js#L44

**Comment by blackMao** [comment]
OK了，多谢啦
