### ISSUE TITLE
import { Select as AntdSelect } from 'antd' 处理错误

### ISSUE THREAD

**Issue by benjycui** [ant-design/babel-plugin-antd#32]
好像是把 alias 当成包名处理了？

```bash
Cannot resolve module 'antd/lib/antd-select'
```

**Comment by yesmeck** [comment]
奇怪我看[测试](https://github.com/ant-design/babel-plugin-antd/blob/master/test/fixtures/specifier-alias/actual.js)是过的

**Comment by yesmeck** [comment]
发现有这样的才会出错:

```javascript
const Option = AntdSelect.Option
```

**Comment by gera2ld** [comment]
这个问题又出现了，这一行导致的：https://github.com/ant-design/babel-plugin-import/blob/d2413b95e418ba7fa2a203e7f9c30cc37afd1e68/src/Plugin.js#L87

**Comment by viruscamp** [comment]
我觉得你们这边好几个 bug #274 #296 都是因为改了 alias 导致的. 谁能告诉我改 alias 有什么必要性?  
不改 alias 的话 只要处理 ImportDeclaration 就行, 现在你们这有十几种 node 要处理, 就为了换掉 alias. 代码看着头疼.
```javascript
import { Button } from 'antd';

      ↓ ↓ ↓ ↓ ↓ ↓
      
var _button = require('antd/lib/button');
require('antd/lib/button/style/css');

// 有什么不好?
var Button = require('antd/lib/button');
require('antd/lib/button/style/css');
```

广告:  
我 fork 的 https://github.com/viruscamp/babel-plugin-transform-imports 实现了 babel-plugin-import 所有功能, 没有这个 bug. 因为我这个不改 alias , 只需要 ImportDeclaration , 代码量也小了一些.

Ad:  
https://github.com/viruscamp/babel-plugin-transform-imports has all the features of babel-plugin-import without this bug.
