### ISSUE TITLE
.babelrc error using babel-plugin-antd with meteorjs

### ISSUE THREAD

**Issue by kvetoslavnovak** [ant-design/babel-plugin-antd#33]
Hi, I am trying to use great react UI library ant-design with meteor https://www.meteor.com/
It works ok via npm install.

But when I want to load components modularly with babel-plugin-antd via .babelrc file I have problems.

With this .babelrc it loads antd components modulalry ok but without styling:
{
"plugins": [
["antd"]
]
}

But with this .babelrc (which should load also css/less modulalry) I got errors:
{
"plugins": [
["antd", {
"style": true
}]
]
}

Console error message:
=> Errors prevented startup:

While processing files with ecmascript (for target web.browser):

/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/buffer.js:329:12:
/imports/ui/App.jsx: Cannot read property '0' of null
at CodeGenerator._push
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/buffer.js:329:12)
at CodeGenerator.push
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/buffer.js:298:10)
at CodeGenerator.Identifier
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/generators/types.js:44:8)
at CodeGenerator._print
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/printer.js:177:17)
at
/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/printer.js:113:14
at CodeGenerator.withSource
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/buffer.js:275:5)
at CodeGenerator.print
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/printer.js:112:10)
at CodeGenerator.ImportSpecifier
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/generators/modules.js:22:8)
at CodeGenerator._print
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/printer.js:177:17)
at
/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/printer.js:113:14
at CodeGenerator.withSource
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/buffer.js:275:5)
at CodeGenerator.print
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/printer.js:112:10)
at CodeGenerator.printJoin
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/printer.js:213:12)
at CodeGenerator.ImportDeclaration
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/generators/modules.js:142:12)
at CodeGenerator._print
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/printer.js:177:17)
at
/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/printer.js:113:14
at CodeGenerator.withSource
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/buffer.js:275:5)
at CodeGenerator.print
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/printer.js:112:10)
at CodeGenerator.printJoin
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/printer.js:213:12)
at CodeGenerator.printSequence
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/printer.js:267:17)
at CodeGenerator.Program
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/generators/base.js:20:8)
at CodeGenerator._print
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/printer.js:177:17)
at
/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/printer.js:113:14
at CodeGenerator.withSource
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/buffer.js:275:5)
at CodeGenerator.print
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/printer.js:112:10)
at CodeGenerator.File
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/generators/base.js:11:8)
at CodeGenerator._print
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/printer.js:177:17)
at
/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/printer.js:113:14
at CodeGenerator.withSource
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/buffer.js:275:5)
at CodeGenerator.print
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/printer.js:112:10)
at CodeGenerator.generate
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/index.js:176:10)
at exports.default
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/index.js:20:14)
at File.generate
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/index.js:694:48)
at File.transform
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/index.js:553:17)
at
/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/pipeline.js:73:19
at File.wrap
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/index.js:563:16)
at Pipeline.transformFromAst
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/pipeline.js:70:17)
at
/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/index.js:60:8
at Cache.Cp.get
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/cache.js:94:19)
at Object.compile
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/index.js:47:23)
at Object.Babel.compile (packages/babel-compiler/babel.js:26:1)
at packages/babel-compiler/babel-compiler.js:109:1
at Function.time (/tools/tool-env/profile.js:305:10)
at profile (packages/babel-compiler/babel-compiler.js:139:1)
at BabelCompiler.BCp.processOneFileForTarget (packages/babel-compiler/babel-compiler.js:108:1)
at BabelCompiler. (packages/babel-compiler/babel-compiler.js:21:1)
at Array.forEach (native)
at BabelCompiler.BCp.processFilesForTarget (packages/babel-compiler/babel-compiler.js:20:1)

While processing files with ecmascript (for target os.linux.x86_64):

/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/buffer.js:329:12:
/imports/ui/App.jsx: Cannot read property '0' of null
at CodeGenerator._push
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/buffer.js:329:12)
at CodeGenerator.push
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/buffer.js:298:10)
at CodeGenerator.Identifier
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/generators/types.js:44:8)
at CodeGenerator._print
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/printer.js:177:17)
at
/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/printer.js:113:14
at CodeGenerator.withSource
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/buffer.js:275:5)
at CodeGenerator.print
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/printer.js:112:10)
at CodeGenerator.ImportSpecifier
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/generators/modules.js:22:8)
at CodeGenerator._print
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/printer.js:177:17)
at
/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/printer.js:113:14
at CodeGenerator.withSource
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/buffer.js:275:5)
at CodeGenerator.print
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/printer.js:112:10)
at CodeGenerator.printJoin
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/printer.js:213:12)
at CodeGenerator.ImportDeclaration
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/generators/modules.js:142:12)
at CodeGenerator._print
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/printer.js:177:17)
at
/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/printer.js:113:14
at CodeGenerator.withSource
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/buffer.js:275:5)
at CodeGenerator.print
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/printer.js:112:10)
at CodeGenerator.printJoin
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/printer.js:213:12)
at CodeGenerator.printSequence
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/printer.js:267:17)
at CodeGenerator.Program
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/generators/base.js:20:8)
at CodeGenerator._print
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/printer.js:177:17)
at
/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/printer.js:113:14
at CodeGenerator.withSource
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/buffer.js:275:5)
at CodeGenerator.print
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/printer.js:112:10)
at CodeGenerator.File
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/generators/base.js:11:8)
at CodeGenerator._print
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/printer.js:177:17)
at
/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/printer.js:113:14
at CodeGenerator.withSource
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/buffer.js:275:5)
at CodeGenerator.print
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/printer.js:112:10)
at CodeGenerator.generate
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/index.js:176:10)
at exports.default
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/node_modules/babel-generator/lib/index.js:20:14)
at File.generate
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/index.js:694:48)
at File.transform
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/index.js:553:17)
at
/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/pipeline.js:73:19
at File.wrap
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/index.js:563:16)
at Pipeline.transformFromAst
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/pipeline.js:70:17)
at
/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/index.js:60:8
at Cache.Cp.get
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/cache.js:94:19)
at Object.compile
(/home/developer/.meteor/packages/ecmascript/.0.4.5.1qjeacz++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/index.js:47:23)
at Object.Babel.compile (packages/babel-compiler/babel.js:26:1)
at packages/babel-compiler/babel-compiler.js:109:1
at Function.time (/tools/tool-env/profile.js:305:10)
at profile (packages/babel-compiler/babel-compiler.js:139:1)
at BabelCompiler.BCp.processOneFileForTarget (packages/babel-compiler/babel-compiler.js:108:1)
at BabelCompiler. (packages/babel-compiler/babel-compiler.js:21:1)
at Array.forEach (native)
at BabelCompiler.BCp.processFilesForTarget (packages/babel-compiler/babel-compiler.js:20:1)

=> Your application has errors. Waiting for file change.

**Comment by kvetoslavnovak** [comment]
After some test I can confirm that the  problem is with the antd babel plugin not Meteor.
It works just fine without style option. But does not work when style option is enabled (less as well as css).

**Comment by ziben** [comment]
I've got this problem too.

My solution is not use the style option in the .babelrc file.

Then import the full style file use "@import '{}/node_modules/antd/dist/antd.less';".

**Comment by jasonHzq** [comment]
An asesome plugin! Bug I've got this problem too without using meteorjs.

**Comment by razagill** [comment]
@kvetoslavnovak @jasonHzq Did you guys find a solution?

**Comment by sorrycc** [comment]
Not the problem in babel-plugin-antd? And I don't have experience with meterjs.
