### ISSUE TITLE
imports striped out

### ISSUE THREAD

**Issue by kubijo** [ant-design/babel-plugin-antd#34]
Hello.

I have configured the plugin by .babelrc (`["antd", { style: "css" }]`) and use es6 destructuring imports.
The problem is however, that those imports are not replaced but merely removed (resulting build has all other imports, but those from antd package.

Have you encoutered this problem?
I was not able pinpoint anything that should do this in my webpack config.

**Comment by sorrycc** [comment]
No, old imports will be removed. https://github.com/ant-design/babel-plugin-antd/blob/773715b6eb46e8e89b055bdce4f875e14d361d2d/src/core.js#L68

**Comment by kubijo** [comment]
Well, how should it work then? I did not get require calls instead.

In the end I just started to use require calls pointing to those lib files directly.
