### ISSUE TITLE
还是不会使用 babel-plugin-antd

### ISSUE THREAD

**Issue by Witee** [ant-design/babel-plugin-antd#35]
cat package.json
{
  "name": "comment",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "admin-lte": "^2.3.3",
    "angularic-ionicon": "^1.1.0",
    "antd": "^1.6.2",
    "babel-core": "^5.8.20",
    "babel-loader": "^5.3.2",
    "babel-polyfill": "^6.7.4",
    "css-loader": "^0.23.1",
    "file-loader": "^0.8.5",
    "font-awesome": "^4.6.1",
    "highcharts": "^4.2.5",
    "history": "^2.1.1",
    "jquery": "^2.2.3",
    "less-loader": "^2.2.3",
    "moment": "^2.13.0",
    "react": "^0.14.3",
    "react-bootstrap": "^0.29.4",
    "react-dom": "^0.14.3",
    "react-highcharts": "^8.3.2",
    "react-loading": "0.0.9",
    "react-router": "^2.4.0",
    "style-loader": "^0.13.1",
    "webpack": "^1.12.9"
  },
  "devDependencies": {
    "babel-plugin-antd": "^0.4.0"
  }
}

#####
[Witee@Witees-MBP v5 ]$ cat webpack.config.js
var webpack = require('webpack');
var path = require("path");

module.exports = {
    entry: "./apps/entry.js",
    output: {
        path: path.join(__dirname, "./static/"),
        filename: "/js/bundle.js"
    },
    resolve: {
        extensions: ["", ".js", ".jsx"]
    },
    plugins: [
       new webpack.ProvidePlugin({
         $: "jquery",
         jQuery: "jquery",
         "window.jQuery": "jquery"
       })
     ],
    module: {
        loaders: [
            {test: /\.css$/, loaders: ['style-loader', 'css-loader']},
            {test: /\.less$/, loaders: ['style-loader', 'css-loader', 'less-loader']},
            {test: /\.js$/, loaders: ['babel-loader'], exclude: /(node_modules|bower_components)/},
            {test: /\.(ttf|eot|svg|woff2|woff)(\?.*)?$/, loader: "file-loader", query: {name: "/fonts/[name]-[hash].[ext]"}},
            {test: /\.jpe?g$|\.gif$|\.png$/, loader: "file-loader", query: {name: "/images/[name]-[hash].[ext]"}}
        ]
    },
    babel: {
    "plugins": [["antd", {"style" : "css"}]],
    }
}

###加上babel这段后会报错：
^C[Witee@Witees-MBP v5 ]$ ./webpack_dev.sh
  0% compilehttps://localhost:8080/webpack-dev-server/
webpack result is served from /
content is served from /Users/xiewt/learnPython/hydra/v5/static
Hash: a64dc3ee044410ba5251
Version: webpack 1.13.0
Time: 758ms

ERROR in ./apps/entry.js
Module build failed: TypeError: The plugin ["antd",{"style":"css"}] didn't export a Plugin instance
    at PluginManager.validate (/Users/xiewt/learnPython/hydra/v5/node_modules/babel-core/lib/transformation/file/plugin-manager.js:164:13)
    at PluginManager.add (/Users/xiewt/learnPython/hydra/v5/node_modules/babel-core/lib/transformation/file/plugin-manager.js:213:10)
    at File.buildTransformers (/Users/xiewt/learnPython/hydra/v5/node_modules/babel-core/lib/transformation/file/index.js:237:21)
    at new File (/Users/xiewt/learnPython/hydra/v5/node_modules/babel-core/lib/transformation/file/index.js:139:10)
    at Pipeline.transform (/Users/xiewt/learnPython/hydra/v5/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at transpile (/Users/xiewt/learnPython/hydra/v5/node_modules/babel-loader/index.js:12:22)
    at Object.module.exports (/Users/xiewt/learnPython/hydra/v5/node_modules/babel-loader/index.js:71:12)
webpack: bundle is now VALID.

主要是  Module build failed: TypeError: The plugin ["antd",{"style":"css"}] didn't export a Plugin instance  

求大神帮忙！

**Comment by Witee** [comment]
由上起来再看看，还是没人回复。

**Comment by sorrycc** [comment]
不支持 babel 5，babel 版本需要是 6。
