### ISSUE TITLE
The plugin ["antd",{"style":"css"}] didn't export a Plugin instance

### ISSUE THREAD

**Issue by JJAWX** [ant-design/babel-plugin-antd#36]
配置如下,为什么出错呢：
.babelrc文件内容:
{
  "stage": 2,
  "env": {
    "development": {
      "plugins": [
        "react-transform",
        ["antd",{"style":"css"}]
      ],
      "extra": {
        "react-transform": {
          "transforms": [{
            "transform": "react-transform-hmr",
            "imports": ["react"],
            "locals":  ["module"]
          }]
        }
      }
    }
  }
}

**Comment by Witee** [comment]
Module build failed: TypeError: The plugin ["antd",{"style":"css"}] didn't export a Plugin instance

我是这个错误。你的呢

**Comment by sorrycc** [comment]
不支持 babel 5，babel 版本需要是 6。
