### ISSUE TITLE
Cannot read property '0' of null

### ISSUE THREAD

**Issue by razagill** [ant-design/babel-plugin-antd#43]
Hi,
So I'm trying to use antd with this babel plugin but anytime I import a module it gives me the following error:
e.g: ```Import { Input } from 'antd';```

and in ```render()```:
```<Input addonBefore="Http://" addonAfter=".com" defaultValue="mysite" />```

gives the following error:
```Cannot read property '0' of null```

I'm using ```.babelrc```. Importing only ```javascript``` works however when I pass in the value for style it gives the above error again.

**Comment by sorrycc** [comment]
Provide a repo that can reproduce this problem?

**Comment by razagill** [comment]
@sorrycc I'll get on it, in the meanwhile check this as well #33 , these guys are having the same problem. (Maybe a duplicate issue)

**Comment by razagill** [comment]
@sorrycc Tried it in a brand new repo and it works. So the problem is with my repo however due to it being a private project I unfortunately can't post the repo. However, I can provide my config files etc.
Just another tid bit, I'm using bootstrap css. I actually wanted to incorporate a few components of antd to see how it fits and that's why I wanted to include only the modular css/js of the component.
