### ISSUE TITLE
babel-plugin-antd 的 style 设为 less 时和默认的 css-modules 配置配合样式失效

### ISSUE THREAD

**Issue by afc163** [ant-design/babel-plugin-antd#46]
当 style 设为 less 或 true 时，这段代码会导致此插件失效：https://github.com/ant-design/antd-init/blob/1.1.0/boilerplates/plain-react/webpack.config.js#L21-L29

设为 css 时没有问题。

same problem: https://github.com/ant-design/ant-design/issues/193#issuecomment-236117824

**Comment by sorrycc** [comment]
解决：

修改 `webpack.config.js` 里处理 css-modules 部分的代码为：(好复杂，atool-build@1.0 里内置 css-modules 吧)

```javascript
// Support CSS Modules
// Parse all less files as css module.
webpackConfig.module.loaders.forEach(function(loader, index) {
  if (typeof loader.test === 'function' && loader.test.toString().indexOf('\\.less$') > -1) {
    loader.include = /node_modules/;
    loader.test = /\.less$/;
  }
  if (loader.test.toString() === '/\\.module\\.less$/') {
    loader.exclude = /node_modules/;
    loader.test = /\.less$/;
  }
  if (typeof loader.test === 'function' && loader.test.toString().indexOf('\\.css$') > -1) {
    loader.include = /node_modules/;
    loader.test = /\.css$/;
  }
  if (loader.test.toString() === '/\\.module\\.css$/') {
    loader.exclude = /node_modules/;
    loader.test = /\.css$/;
  }
});
```

详见：https://github.com/ant-design/antd-init/commit/84df1860a6c4407b6e87d5c944a5d81b1ae71de6

**Comment by nianhua110** [comment]
为了ａｎｔｄ的基色符合我们的产品，我按照ａｎｔｄ给的修改方案操作，可是没有成功。
首先ｄｖａ－ｃｌｉ生成的工程，然后添加了
```
  webpackConfig.babel.plugins.push(['import', {
    libraryName: 'antd',
    style: 'css'  // if true, use less
  }]);
```
最终的webpack.config.js 如下
```
const webpack = require('atool-build/lib/webpack');

module.exports = function(webpackConfig, env) {
  webpackConfig.babel.plugins.push('transform-runtime');
  webpackConfig.babel.plugins.push(['import', {
    libraryName: 'antd',
    style: 'less'  // if true, use less
  }]);

  // Support hmr
  if (env === 'development') {
    webpackConfig.devtool = '#eval';
    webpackConfig.babel.plugins.push('dva-hmr');
  } else {
    webpackConfig.babel.plugins.push('dev-expression');
  }

  // Don't extract common.js and common.css
  // webpackConfig.plugins = webpackConfig.plugins.filter(function(plugin) {
  //   return !(plugin instanceof webpack.optimize.CommonsChunkPlugin);
  // });

  // Support CSS Modules
  // Parse all less files as css module.
  webpackConfig.module.loaders.forEach(function(loader, index) {
    if (typeof loader.test === 'function' && loader.test.toString().indexOf('\\.less$') > -1) {
      loader.include = /node_modules/;
      loader.test = /\.less$/;
    }
    if (loader.test.toString() === '/\\.module\\.less$/') {
      loader.exclude = /node_modules/;
      loader.test = /\.less$/;
    }
    if (typeof loader.test === 'function' && loader.test.toString().indexOf('\\.css$') > -1) {
      loader.include = /node_modules/;
      loader.test = /\.css$/;
    }
    if (loader.test.toString() === '/\\.module\\.css$/') {
      loader.exclude = /node_modules/;
      loader.test = /\.css$/;
    }
  });

  return webpackConfig;
};
```
但是，依然页面失去了样式

**Comment by huhao642178633** [comment]
var webpack = require('webpack');
var path = require('path');

module.exports = {
  entry: {
    app: [
      'webpack/hot/dev-server',
      'webpack-dev-server/client?http://localhost:8080',
      './App/IndexView.jsx'
    ],
  },
  output: {
    filename: 'bundle.js',
    publicPath: ''
  },
  module: {
    loaders: [
      // { test: /\.js$/, exclude: /node_modules/, 
      //   loader: 'babel-loader?presets[]=es2015&presets[]=react' },

      {
        test: /\.(js|jsx)$/, exclude: /node_modules/, loader: 'babel-loader',
        query: {
          presets: ['es2015', 'react'],
          plugins: [
            ['import', [{ libraryName: "antd", style: 'css' }]],
          ],
        },
        //include: path.join(__dirname, '.')
      },
      //{ test: /\.css$/, loader: 'style-loader!css-loader' },
      //{ test: /\.css$/, loader: 'style-loader!css-loader?modules' },
      { test: /\.css$/, loader: 'style-loader!css-loader' },
      { test: /\.less$/,loader: 'style!css!less' },
      { test: /\.(png|jpg)$/, loader: 'url-loader?limit=8192' },

    ],
  },
  resolve: {
    extensions: ['.js', '.json', '.jsx']
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin()
  ],

};
