### ISSUE TITLE
antd可以和antd-mobile一起使用吗？这么设置似乎不行

### ISSUE THREAD

**Issue by tungh** [ant-design/babel-plugin-antd#55]
```javascript
{
  "presets": [
    "react"
  ],
  "plugins": [
    [
      {
        "libraryName": "antd",
        "libraryDirectory": "lib", // default: lib
        "style": true
      },
      {
        "libraryName": "antd-mobile",
        "libraryDirectory": "component"
      }
    ],
    [
      "transform-runtime",
      {
        "polyfill": false,
        "regenerator": true
      }
    ]
  ]
}
```

**Comment by sorrycc** [comment]
```javascript
{
  "presets": [
    "react"
  ],
  "plugins": [
    ['antd', [
      {
        "libraryName": "antd",
        "libraryDirectory": "lib", // default: lib
        "style": true
      },
      {
        "libraryName": "antd-mobile",
        "libraryDirectory": "component"
      }
    ]],
    [
      "transform-runtime",
      {
        "polyfill": false,
        "regenerator": true
      }
    ]
  ]
}
```

**Comment by tungh** [comment]
感谢，但是样式没有生效，版本没错。"babel-plugin-antd": "^0.5.1", 并且在console还是提示
You are using prebuilt antd,
please use https://github.com/ant-design/babel-plugin-antd to reduce app bundle size.

import { DatePicker, List } from 'antd-mobile';
import { Button } from 'antd';
import { createForm } from 'rc-form';
import React from 'react';
import ReactDOM from 'react-dom';

function onChange(value) {
  console.log('选择了时间：', value);
}

let MobileDemo = React.createClass({

  render() {
    return (<div>
      <List>
        <List.Header>选择时间</List.Header>
        <List.Body>
          <DatePicker
            mode="datetime"
            {...this.props.form.getFieldProps('datetime')}
          >
            <List.Item arrow="horizontal">日期+时间</List.Item>
          </DatePicker>
        </List.Body>
      </List>
      <div>换行</div>
      <div>
    <Button type="primary">Primary</Button>
    <Button>Default</Button>
    <Button type="ghost">Ghost</Button>
    <Button type="dashed">Dashed</Button>
  </div>
    </div>
    
    );
  },
});

MobileDemo = createForm()(MobileDemo);

ReactDOM.render(<MobileDemo />, document.getElementById('root'));

**Comment by tungh** [comment]
感谢，但是样式没有生效，版本没错。"babel-plugin-antd": "^0.5.1", 并且在console还是提示
You are using prebuilt antd,
please use https://github.com/ant-design/babel-plugin-antd to reduce app bundle size.

import { DatePicker, List } from 'antd-mobile';
import { Button } from 'antd';
import { createForm } from 'rc-form';
import React from 'react';
import ReactDOM from 'react-dom';

function onChange(value) {
  console.log('选择了时间：', value);
}

let MobileDemo = React.createClass({

  render() {
    return (<div>
      <List>
        <List.Header>选择时间</List.Header>
        <List.Body>
          <DatePicker
            mode="datetime"
            {...this.props.form.getFieldProps('datetime')}
          >
            <List.Item arrow="horizontal">日期+时间</List.Item>
          </DatePicker>
        </List.Body>
      </List>
      <div>换行</div>
      <div>
    <Button type="primary">Primary</Button>
    <Button>Default</Button>
    <Button type="ghost">Ghost</Button>
    <Button type="dashed">Dashed</Button>
  </div>
    </div>
    
    );
  },
});

MobileDemo = createForm()(MobileDemo);

ReactDOM.render(<MobileDemo />, document.getElementById('root'));

**Comment by tungh** [comment]
请问如何一起打包antd和antd-mobile 两个样式文件进css？
这个是https://github.com/ant-design/antd-init/tree/master/boilerplates/MobileDemo

```
// Learn more on how to config.
// - https://github.com/ant-tool/atool-build#配置扩展

const webpack = require('atool-build/lib/webpack');

module.exports = function (webpackConfig) {
  webpackConfig.babel.plugins.push('transform-runtime');
  webpackConfig.babel.plugins.push(['antd', {
    style: 'css',  // if true, use less
    libraryName: 'antd-mobile',
  }]);
  return webpackConfig;
};

```
