### ISSUE TITLE
Module not found: Error: Cannot resolve module 'antd/component/button/style' in /cms/app/components

### ISSUE THREAD

**Issue by OhCoder** [ant-design/babel-plugin-antd#59]
`import {Button} from 'antd'`

直接引用错误，提示：
ERROR in ./app/components/App.jsx
Module not found: Error: Cannot resolve module 'antd/component/button/style' in /Users/xxxx/Documents/cms/app/components
 @ ./app/components/App.jsx 7:13-51

ERROR in ./app/components/App.jsx
Module not found: Error: Cannot resolve module 'antd/component/button' in /Users/xxxx/Documents/cms/app/components
 @ ./app/components/App.jsx 9:14-46

用了webpack 配置alias，不知道跟这个有没有关……

**Comment by sorrycc** [comment]
应该有关。

**Comment by OhCoder** [comment]
装了less和less-loader解决了
