### ISSUE TITLE
Use babel-plugin-antd 样式无效

### ISSUE THREAD

**Issue by motorguo** [ant-design/babel-plugin-antd#61]
```
"babel-plugin-antd": "^0.5.1",
"antd-mobile": "^0.7.8",

npm -v
3.8.9

node -v
v6.2.0
```
## 问题

`//.babelrc`
```
['antd', [
     { libraryName: "antd", libraryDirectory: "lib", style: true,},
     { libraryName: "antd-mobile",libraryDirectory: "component",},
 ]],
```

## 这样用无报错

> **没应用到样式，也没加载进来**

### 这样用

```
import { Button } from 'antd-mobile';
```

> 就没报错了，可是样式还是没有加载进来

**Comment by laolu87** [comment]
`[["antd-mobile", {style:"css"}]]`这样写应该就可以了!

**Comment by kezoo** [comment]
试着添加到webpack的config文件的loader中，如:
`{
          test: /\.js$/,,
          loader: 'babel',
          query: {
            cacheDirectory: true,
            presets: ['es2015', 'react', 'stage-1'],
            plugins: [
              'add-module-exports',
              ["antd", [
                {
                  libraryName: "antd",
                  style: "css",
                },
                {
                  libraryName: "antd-mobile",
                  style: "css",
                },
              ]],
            ],
          },`

**Comment by motorguo** [comment]
@kezoo 

试第一个：`["antd", { style: "css", libraryName: "antd-mobile" }]` ok, 无报错

这样用  `import Button from 'antd-mobile/lib/button';` 样式是完全不出来；

`import { Button } from 'antd-mobile';` 这样用样式倒是出来了，可是 `button` 的样式没出来

出来的样式应该是一些全局的， `normalize.css`的也出来了。

---

我尝试了你说的第二种方法，在`.babelrc` 添加 `["antd-mobile", {style:"css"}]`

`报错`

```
ERROR in ./src/entries/index.js
Module build failed: ReferenceError: Unknown plugin "antd-mobile" specified in
```
---
我不加 `exclude` 这个吧就报错，正常来讲是可以不加的啊。

`//webpack.js loaders`
```
{test: /\.(js|jsx)?$/, loaders: ['babel'], exclude: NM_PATH}
```

`//.babelrc`
```
{
    "presets": ["react", "es2015", "stage-0"],
    "env": {
        "development": {
            "plugins": [
                ["antd", { style: "css", libraryName: "antd-mobile" }],
                ["react-transform", {
                    "transforms": [{
                        "transform": "react-transform-hmr",
                        "imports": ["react"],
                        "locals": ["module"]
                    }, {
                        "transform": "react-transform-catch-errors",
                        "imports": ["react", "redbox-react"]
                    }]
                }],
            ]
        }
    }
}
```

**Comment by motorguo** [comment]
@kezoo 我把 `.babelrc` 的直接放到loaders里也是不行，也测试过你上面那一段，我去掉了 `add-module-exports`

**Comment by motorguo** [comment]
## 已解决
> 在 `webpack loaders` 配置的时候需要把  `css` 和 `cssmodules` 分开处理，
> 并加上 `exclude` or `include`, 不去处理 `am` 样式 。

```
{
    test: /\.css$/,
    loader: 'css?sourceMap&modules&localIdentName=[local]___[hash:base64:5]!!',
    exclude: /node_modules/
},
{
    test: /\.css$/, 
    loader: 'style!css'
},
```

*感谢楼上两位回答*

**Comment by crowphy** [comment]
这样的话自定义样式却无法引入了

**Comment by lylhub** [comment]
{
                    test: /\.css$/, loader: "style!css"
                },
                {
                    test: /\.less$/, loader: "style!css!less"
    },
don‘t use ExtractTextPlugin

**Comment by motorguo** [comment]
@crowphy 把两条 `loader` 顺序换一下

**Comment by motorguo** [comment]
@lylhub 
```
import ExtractTextPlugin from 'extract-text-webpack-plugin';
```

**Comment by funnytina** [comment]
在 webpack loaders 配置的时候需要把 css 和 cssmodules 分开处理，
并加上 exclude or include, 不去处理 am 样式 。
{
    test: /\.css$/,
    loader: 'css?sourceMap&modules&localIdentName=[local]___[hash:base64:5]!!',
    exclude: /node_modules/
},
{
    test: /\.css$/, 
    loader: 'style!css'
},
两条针对css的配置 哪条会生效呢 为何要配2条
配置了这个后，我的font.css报错误了，该怎么解决

**Comment by MingOf** [comment]
@funnytina  我也报错了
```
ERROR in ./node_modules/css-loader!./node_modules/css-loader?{"modules":true,"loacalIdentName":"[name]__[local]_[hash:base64:5]","importLoaders":1}!./src/css/header.css
Module build failed: Unknown word (1:1)

```

**Comment by JX-Zhuang** [comment]
You can see 
https://github.com/ant-design/ant-design/issues/3442#issuecomment-374877201
