### ISSUE TITLE
antd 如何和antd mobile共存？

### ISSUE THREAD

**Issue by Losering** [ant-design/babel-plugin-antd#65]
"plugins": [
          ["antd",
              [
                {
                  "libraryName": "antd",
                  "libraryDirectory": "lib",
                  "style": true

                },
                {
                  "libraryName": "antd-mobile",
                  "libraryDirectory": "component"
                }
              ]
          ]
        ]

import { Button } from 'antd-mobile';

Module not found: Error: Can't resolve 'antd-mobile' in '/Users/liuyi/Work/nevermore/app/containers/Editor'

**Comment by motorguo** [comment]
#55

**Comment by Losering** [comment]
没发现差别呀

**Comment by sorrycc** [comment]
antd-mobile 依赖没安装好?

**Comment by Losering** [comment]
安装好了
